from django.urls import path

from service.views import (
    index,
    ProfessionsListView,
    ProfessionCreateView,
    ProfessionUpdateView,
    ProfessionDeleteView,
    TaskTypesListView,
    TaskTypeCreateView,
    TaskTypeUpdateView,
    TaskTypeDeleteView,
    VehiclesListView,
    VehicleCreateView,
    VehicleDetailView,
    VehicleUpdateView,
    VehicleDeleteView,
    WorkersListView,
    WorkerCreateView,
    WorkerDetailView,
    WorkerUpdateView,
    WorkerDeleteView,
    TasksListView,
    TaskCreateView,
    TaskDetailView,
    TaskUpdateView,
    TaskDeleteView,
    toggle_assign_to_task, update_task_progress,
)

urlpatterns = [
    path("", index, name="index"),
    path(
        "professions/",
        ProfessionsListView.as_view(),
        name="professions-list",
    ),
    path(
        "professions/create/",
        ProfessionCreateView.as_view(),
        name="profession-create",
    ),
    path(
        "professions/<int:pk>/update/",
        ProfessionUpdateView.as_view(),
        name="profession-update",
    ),
    path(
        "professions/<int:pk>/delete/",
        ProfessionDeleteView.as_view(),
        name="profession-delete",
    ),
    path(
        "tasktypes/",
        TaskTypesListView.as_view(),
        name="task-types-list",
    ),
    path(
        "tasktypes/create/",
        TaskTypeCreateView.as_view(),
        name="task-type-create",
    ),
    path(
        "tasktypes/<int:pk>/update/",
        TaskTypeUpdateView.as_view(),
        name="task-type-update",
    ),
    path(
        "tasktypes/<int:pk>/delete/",
        TaskTypeDeleteView.as_view(),
        name="task-type-delete",
    ),
    path(
        "vehicles/",
        VehiclesListView.as_view(),
        name="vehicles-list",
    ),
    path(
        "vehicles/create/",
        VehicleCreateView.as_view(),
        name="vehicle-create",
    ),
    path(
        "vehicles/<int:pk>/",
        VehicleDetailView.as_view(),
        name="vehicle-detail",
    ),
    path(
        "vehicles/<int:pk>/update/",
        VehicleUpdateView.as_view(),
        name="vehicle-update",
    ),
    path(
        "vehicles/<int:pk>/delete/",
        VehicleDeleteView.as_view(),
        name="vehicle-delete",
    ),
    path(
        "workers/",
        WorkersListView.as_view(),
        name="workers-list",
    ),
    path(
        "workers/create/",
        WorkerCreateView.as_view(),
        name="worker-create",
    ),
    path(
        "workers/<int:pk>/",
        WorkerDetailView.as_view(),
        name="worker-detail",
    ),
    path(
        "workers/<int:pk>/update/",
        WorkerUpdateView.as_view(),
        name="worker-update",
    ),
    path(
        "workers/<int:pk>/delete/",
        WorkerDeleteView.as_view(),
        name="worker-delete",
    ),
    path(
        "tasks/",
        TasksListView.as_view(),
        name="tasks-list",
    ),
    path(
        "tasks/create/",
        TaskCreateView.as_view(),
        name="task-create",
    ),
    path(
        "tasks/<int:pk>/",
        TaskDetailView.as_view(),
        name="task-detail",
    ),
    path(
        "tasks/<int:pk>/update/",
        TaskUpdateView.as_view(),
        name="task-update",
    ),
    path(
        "tasks/<int:pk>/delete/",
        TaskDeleteView.as_view(),
        name="task-delete",
    ),
    path(
        "tasks/<int:pk>/toggle-assign/",
        toggle_assign_to_task,
        name="toggle-task-assign",
    ),
    path('tasks/<int:pk>/update-progress', update_task_progress, name='update-task-progress'),

]


app_name = "service"
